version: 2.1
orbs:
  python: circleci/python@1.5.0
jobs:
  build:
    working_directory: .
    docker:
      - image: "circleci/python:latest"
    steps:
      - checkout
      - run: pip install telebot
workflows:
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build